pipeline {
         agent any
         stages {
                 stage('SonarQube Analysis') {
                 steps {
                    input('Do you want to proceed?')
                    withSonarQubeEnv('Sonar') {
                    // requires SonarQube Scanner for Maven 3.2+
                    bat 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar'
                        }
                     }         
                 }
                 stage('Code Build') {
                 steps     {
                       input('Do you want to proceed with build & war creation?')
                       bat 'mvn clean package'
                       echo "war creation successful!!"
                           }
                 }
                 stage('Dev Deployment') {
                 steps {
                       input('Do you want to proceed with Dev deployment?')
                       bat 'cd C:\\Users\\330406\\.jenkins\\workspace\\Job2\\Pipeline\\target\\'
                       bat 'RENAME Pipeline-0.0.1-SNAPSHOT.war Pipeline.war'
                       bat 'copy C:\\Users\\330406\\.jenkins\\workspace\\Job2\\Pipeline\\target\\Pipeline.war D:\\Software\\apache-tomee-plus-7.0.2\\webapps\\'
                       echo "Dev Deployment Successful!!"
                           }
                 }
                 stage('Testing') {
                 steps {
                         echo "Testing Successful!!"
                           }
                 stage('Prod Deployment') {
                 steps {
                       echo "Production Deployment Successful!!"
                           }
                 }
         }
}
