pipeline {
         agent any
         stages {
                 stage('Pull Code from Git') {
                 steps {
                     echo 'Code Build Stage'
                 }
                 }
                 stage('SonarQube Analysis') {
                 steps {
                    input('Do you want to proceed?')
                    withSonarQubeEnv('Sonar') {
                    // requires SonarQube Scanner for Maven 3.2+
                    bat 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar'
                           }
                      }         
                 }
                 stage('Dev Deployment') {
                 steps {
                       input('Do you want to proceed with Dev deployment?')
                       bat cd C:\Users\330406\.jenkins\workspace\Job2\Pipeline\target\
                       bat RENAME Pipeline-0.0.1-SNAPSHOT.war Pipeline.war
                       bat copy C:\Users\330406\.jenkins\workspace\Job2\Pipeline\target\Pipeline.war D:\Software\apache-tomee-plus-7.0.2\webapps\
                       echo "Dev Deployment Successful!!"
                 }
                 }
                 stage('Testing') {
                 parallel { 
                            stage('Unit Test') {
                           steps {
                                echo "Running the unit test..."
                           }
                           }
                            stage('Integration test') {

                              steps {
                                echo "Running the integration test..."
                              }
                           }
                           }
                           }
                 stage('Prod Deployment') {
                 when {
                       not {
                            branch "master"
                       }
                 }
                 steps {
                       echo "Production Deployment Successful!!"
                 }
                 }
              }
}
